import { Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./ThemeContext";
import { images } from "../next.config";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Blogify",
  description: "Generated by create next app",
  
};


export const dynamic = "force-dynamic";


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/blogging.png" sizes="any" />
      </head>

      <body className={outfit.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
